version: "3"

services:
  cache:
    image: valkey/valkey:alpine
    container_name: sainnhe-go-common-cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH}/cache:/data

  db:
    image: postgres:alpine
    container_name: sainnhe-go-common-db
    restart: always
    mem_limit: 500M
    cpus: 0.8
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH}/db:/var/lib/postgresql/data

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: sainnhe-go-common-otel-collector
    restart: always
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
