version: "3"

services:
  cache:
    image: valkey/valkey:alpine
    container_name: teamsorghum-go-common-cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH}/cache:/data

  db:
    image: postgres:alpine
    container_name: teamsorghum-go-common-db
    restart: always
    mem_limit: 500M
    cpus: 0.8
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH}/db:/var/lib/postgresql/data
