version: "2.2"

services:
  cache:
    image: valkey/valkey:alpine
    container_name: teamsorghum-go-common-cache
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ${DATA_PATH}/cache:/data

  db:
    image: postgres:alpine
    container_name: teamsorghum-go-common-db
    restart: always
    mem_limit: 500M
    cpus: 0.8
    env_file: ./.env
    ports:
      - 5432:5432
    volumes:
      - ${DATA_PATH}/db:/var/lib/postgresql/data

  loki:
    image: grafana/loki:latest
    container_name: teamsorghum-go-common-loki
    restart: always
    ports:
      - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:latest
    container_name: teamsorghum-go-common-promtail
    restart: always
    volumes:
      - ${DATA_PATH}/promtail/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    image: grafana/grafana:latest
    container_name: teamsorghum-go-common-grafana
    restart: always
    ports:
      - 3000:3000
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
